<?php require_once '../config/db.php'; require_once '../includes/auth.php'; require_role('faculty');
$msg='';$error='';
$subjects=$pdo->query("SELECT * FROM subjects ORDER BY name")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
$title=trim($_POST['title']??'');$sid=(int)$_POST['subject_id'];$uid=(int)$_POST['unit_id'];$type=$_POST['material_type'];$desc=trim($_POST['description']??'');
if($title===''||!isset($_FILES['pdf_file'])||$_FILES['pdf_file']['error']!==UPLOAD_ERR_OK)$error='Title, subject and PDF file are required.';
else{$file=$_FILES['pdf_file'];$ext=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION));$allowed=['pdf'];if(!in_array($ext,$allowed,true)||$file['size']>10*1024*1024)$error='Only PDF files up to 10 MB are allowed.';
else{$new=uniqid('mat_',true).'.pdf';$dir=__DIR__.'/../uploads/';if(!is_dir($dir))mkdir($dir,0775,true);if(move_uploaded_file($file['tmp_name'],$dir.$new)){$st=$pdo->prepare("INSERT INTO materials(title,subject_id,unit_id,material_type,description,file_name,file_path,uploaded_by,status) VALUES(?,?,?,?,?,?,?,?, 'approved')");$st->execute([$title,$sid,$uid?:null,$type,$desc,$file['name'],$new,$_SESSION['user_id']]);$msg='Material uploaded successfully.';}else$error='File upload failed.';}}
}
$units=$pdo->query("SELECT * FROM units ORDER BY subject_id,unit_no")->fetchAll();
$page_title='Upload Study Material';$css_path='../assets/css/style.css';$home_path='dashboard.php';$logout_path='../logout.php';$role='faculty';include '../includes/header.php';?><div class="layout"><?php include '../includes/sidebar.php';?><h1 class="page-title">Upload Study Material</h1><?php if($msg):?><div class="alert success"><?=e($msg)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?><div class="form-card"><form method="post" enctype="multipart/form-data"><label>Title *</label><input name="title" placeholder="Enter title" required><div class="form-row"><div><label>Subject *</label><select name="subject_id" required><option value="">Select Subject</option><?php foreach($subjects as $s):?><option value="<?=$s['id']?>"><?=e($s['name'])?></option><?php endforeach;?></select></div><div><label>Unit</label><select name="unit_id"><option value="">All Units</option><?php foreach($units as $u):?><option value="<?=$u['id']?>"><?=e($u['unit_name'])?></option><?php endforeach;?></select></div></div><label>Material Type *</label><select name="material_type" required><option value="unit_notes">Unit Notes</option><option value="question_paper">Question Paper</option><option value="important_questions">Important Questions</option><option value="lab_material">Lab Materials</option><option value="reference_material">Reference Materials</option></select><label>Description</label><textarea name="description" placeholder="Enter description..."></textarea><label>PDF File * (max 10 MB)</label><input type="file" name="pdf_file" accept=".pdf" required><button class="btn green">Upload Material</button></form></div></main></div><?php include '../includes/footer.php';?>